# Book settings
title: "INF 133 Fall 2020"
author: Mark S. Baldwin
logo: logo_stacked.png
copyright: "2020"

parse:
  myst_extended_syntax: true
repository:
  url: http://inf133-fa20.markbaldw.in/
  path_to_book: /
latex:
  latex_documents:
    targetname: book.tex
